name: Build and Test

on:
  push:
    branches: [ Development, Production, main ]
  pull_request:
    branches: [ Development, Production, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install GTK dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gtk-sharp3 libwebkit2gtk-4.0-dev
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Create self-contained release
      run: dotnet publish -r linux-x64 --self-contained true -c Release
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kolbeh-linux-release
        path: bin/Release/net6.0/linux-x64/publish/
